version: '3'

services: 
  earth:
    image: earth
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - ./earth.env
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - backend
    depends_on: 
      - redis-auth
      - cassandra

  redis-auth:
    image: "redis"
    ports: 
      - "127.0.0.1:10332:6379"
    restart: on-failure
    networks: 
      - backend

  cassandra:
    image: cassandra
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./data:/var/lib/cassandra
    expose: 
      - '6000'
      - '7000'
      - '7001'
      - '9042'
    ports:
      - '127.0.0.1:10333:9042'
    networks: 
      - backend

  cassandra-web:
    image: cassandra-ui
    build: 
      context: .
      dockerfile: Dockerfile.cassandra-ui
    environment: 
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    depends_on: 
      - cassandra
    ports:
      - '10334:3000'
    networks: 
      - backend




networks: 
  backend: